keywords = [
    "phd",
    "doctorate",
    "doctoral position",
    "call for application",
    "CFA",
    "doctoral fellowship",
    "position",
    "metaphysics",
    "logic",
]

telegram_chat_id = "6978630483"
